### ISSUE TITLE
Clean UP & Dockerization eos5axz

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos5axz#6]

**Comment by simrantan** [comment]
@GemmaTuron 
Completed refactoring and submitted a PR!

**Comment by GemmaTuron** [comment]
@simrantan 
Please see my comment on the PR.

**Comment by simrantan** [comment]
I am working on adding the main.py and service.py. I have spent a while editing these files to match the format in eos-template, and I have been testing repeatedly to check functionality, finding errors and fixing them as I go. I've gotten a little stuck on this error that has shown up in the fetch (and the PR workflow) - 
`  File "/usr/share/miniconda/envs/eos5axz/lib/python3.7/site-packages/bentoml/service/artifacts/__init__.py", line 181, in wrapped_save
    return original(*args, **kwargs)
  File "/home/runner/eos/dest/eos5axz/src/service.py", line 143, in save
    self._copy_checkpoints(dst)
  File "/home/runner/eos/dest/eos5axz/src/service.py", line 108, in _copy_checkpoints
    src_folder = self._model.checkpoints_dir
AttributeError: 'NoneType' object has no attribute 'checkpoints_dir'`

This is the code it is referring to - 
` def __init__(self, name):
        super(Artifact, self).__init__(name)
        self._model = None
        self._extension = ".pkl"

    def _copy_checkpoints(self, base_path):
        src_folder = self._model.checkpoints_dir
        dst_folder = os.path.join(base_path, "checkpoints")
        if os.path.exists(dst_folder):
            os.rmdir(dst_folder)
        shutil.copytree(src_folder, dst_folder)
`
I took this code from eos-template and looked at multiple other models as examples, so I am unsure why this Nonetype error is occruring. I'm planning to spend more time looking at this tomorrow but if there are any tips/solutions it would be much appreciated!

**Comment by GemmaTuron** [comment]
Hi @simrantan 

There are no checkpoints for this model, so we should not try to save them. the file can be a much simpler version, unless we decide to keep it different, like https://github.com/ersilia-os/eos3b5e/
@miquelduranfrigola can you let us know what you prefer? this is the Morgan Counts, which is also used by ZairaChem

**Comment by simrantan** [comment]
I have tried to remove the need for tracking checkpoints, and have gotten the same error as above for framework_dir now so I think the issue lies with the _model object:

  File "/usr/share/miniconda/envs/eos5axz/lib/python3.7/site-packages/bentoml/service/artifacts/__init__.py", line 181, in wrapped_save
    return original(*args, **kwargs)
  File "/home/runner/eos/dest/eos5axz/src/service.py", line 135, in save
    self._copy_framework(dst)
  File "/home/runner/eos/dest/eos5axz/src/service.py", line 110, in _copy_framework
    src_folder = self._model.framework_dir
AttributeError: 'NoneType' object has no attribute 'framework_dir'

I can see that  the code that where this occurs is this: 
` def __init__(self, name):
        super(Artifact, self).__init__(name)
        self._model = None
        self._extension = ".pkl"

    def _copy_framework(self, base_path):
        src_folder = self._model.framework_dir
        dst_folder = os.path.join(base_path, "framework")
        if os.path.exists(dst_folder):
            os.rmdir(dst_folder)
        shutil.copytree(src_folder, dst_folder)`
self._model is declared None, but all models have this line in service.py so I'm not sure why this code is identifying it as an issue.
Is this worth continuing work on or should I revert it to the original form (+any refactoring needed) and submit?

**Comment by GemmaTuron** [comment]
Hi @simrantan 
I think we can then leave the model as it was, since it is a very small implementation. @miquelduranfrigola ?

**Comment by GemmaTuron** [comment]
@simrantan 

I've closed the PR to avoid mixing code. I suggest taking the code as it was and simply making sure we use the api RUN not PREDICT.
Thanks :)
